package com.example.retailsafetymonitor.domain.repository

import com.example.retailsafetymonitor.domain.model.SafetyReport
import kotlinx.coroutines.flow.Flow

/**
 * Domain-layer contract for [SafetyReport] persistence operations.
 *
 * Reports are write-once: once generated by [GenerateSafetyReportUseCase] and saved,
 * they are never updated. [getLatestReport] and [getAllReports] return [Flow] so that
 * [ReportViewModel] re-renders automatically after [WeeklyReportWorker] inserts a new report.
 *
 * Implemented by [ReportRepositoryImpl]; bound via Hilt in [RepositoryModule].
 */
// S: Single Responsibility — declares report query and insert operations; no scoring logic
// D: Dependency Inversion — ReportViewModel and use cases depend on this interface, not Room
interface ReportRepository {

    /**
     * Returns a live [Flow] emitting the single most recently generated [SafetyReport],
     * or null if no report has been created yet.
     * Emits on every Room write to the reports table.
     */
    fun getLatestReport(): Flow<SafetyReport?>

    /**
     * Returns a live [Flow] of all generated reports ordered newest-first.
     * Used by [ReportViewModel] to populate the report history list.
     */
    fun getAllReports(): Flow<List<SafetyReport>>

    /**
     * Persists a newly generated [report] to Room. Uses REPLACE conflict strategy,
     * so re-running generation for the same week window overwrites the previous entry.
     *
     * @param report The completed [SafetyReport] to save.
     */
    suspend fun insertReport(report: SafetyReport)
}
