package com.example.retailsafetymonitor.ui.report

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.retailsafetymonitor.domain.model.SafetyReport
import com.example.retailsafetymonitor.domain.repository.ReportRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.flow.map
import javax.inject.Inject

/**
 * Immutable snapshot of the Report screen state.
 *
 * @property latestReport The most recently generated [SafetyReport], or null if none exist yet.
 * @property allReports Full list of reports ordered newest-first.
 * @property isLoading True until the first Room emission resolves the initial loading state.
 */
data class ReportUiState(
    val latestReport: SafetyReport? = null,
    val allReports: List<SafetyReport> = emptyList(),
    val isLoading: Boolean = true
)

/**
 * ViewModel for [ReportScreen]. Exposes the report history stream from [ReportRepository].
 *
 * Reports are generated by [WeeklyReportWorker] (background) or [DashboardViewModel.generateWeeklyReport]
 * (on-demand). This ViewModel is read-only — it observes the Room reports table and renders the result.
 *
 * Follows Unidirectional Data Flow (UDF):
 * - Events flow UP from UI via public functions
 * - State flows DOWN to UI via [uiState] StateFlow
 * - No direct state mutation from the UI layer
 */
@HiltViewModel
class ReportViewModel @Inject constructor(
    private val reportRepository: ReportRepository
) : ViewModel() {

    /**
     * Live [StateFlow] of [ReportUiState] derived from the Room reports stream.
     * [isLoading] is false as soon as the first Room emission arrives (even if empty).
     */
    val uiState: StateFlow<ReportUiState> = reportRepository.getAllReports().map { reports ->
        ReportUiState(
            latestReport = reports.firstOrNull(),
            allReports = reports,
            isLoading = false
        )
    }.stateIn(viewModelScope, SharingStarted.WhileSubscribed(5_000), ReportUiState())
}
