package com.example.retailsafetymonitor.ui.report

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Card
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import com.example.retailsafetymonitor.ui.components.ComplianceGauge
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Scrollable screen displaying the latest AI-generated weekly safety report.
 *
 * States:
 * - Loading: [CircularProgressIndicator] while Room emits the first value.
 * - No report: placeholder card prompting the user to generate one from the Dashboard.
 * - Report available: metadata card, [ComplianceGauge], weekly stats card, AI summary card.
 *
 * Reports are generated by [WeeklyReportWorker] (background, 7-day schedule) or on demand
 * by [DashboardViewModel.generateWeeklyReport]. This screen is read-only.
 *
 * @param viewModel Hilt-injected [ReportViewModel].
 */
@Composable
fun ReportScreen(viewModel: ReportViewModel = hiltViewModel()) {
    val uiState by viewModel.uiState.collectAsState()
    val dateFormat = SimpleDateFormat("MMM dd, yyyy", Locale.getDefault())

    Column(
        modifier = Modifier
            .fillMaxSize()
            .verticalScroll(rememberScrollState())
            .padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        Text("AI Safety Report", style = MaterialTheme.typography.headlineMedium, fontWeight = FontWeight.Bold)

        when {
            uiState.isLoading -> CircularProgressIndicator(modifier = Modifier.align(Alignment.CenterHorizontally))
            uiState.latestReport == null -> {
                Card(modifier = Modifier.fillMaxWidth()) {
                    Text(
                        "No report generated yet. Use the Dashboard to generate your first weekly report.",
                        modifier = Modifier.padding(16.dp),
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
            }
            else -> {
                val report = uiState.latestReport!!

                // Report metadata
                Card(modifier = Modifier.fillMaxWidth()) {
                    Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(4.dp)) {
                        Text("Week of ${dateFormat.format(Date(report.weekStartDate))}",
                            style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.SemiBold)
                        Text("Generated: ${dateFormat.format(Date(report.generatedAt))}",
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant)
                    }
                }

                // Compliance Score
                ComplianceGauge(
                    score = report.complianceScore,
                    modifier = Modifier.align(Alignment.CenterHorizontally)
                )

                // Stats
                Card(modifier = Modifier.fillMaxWidth()) {
                    Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) {
                        Text("Weekly Summary", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.SemiBold)
                        Text("Total hazards: ${report.totalHazards}")
                        Text("Resolved: ${report.resolvedHazards}")
                        Text("Unresolved: ${report.totalHazards - report.resolvedHazards}")
                        if (report.topHazardTypes.isNotEmpty()) {
                            Text("Top risks: ${report.topHazardTypes.joinToString { it.displayName }}")
                        }
                    }
                }

                // AI Summary
                Card(modifier = Modifier.fillMaxWidth()) {
                    Column(modifier = Modifier.padding(16.dp)) {
                        Text("AI Analysis", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.SemiBold)
                        Spacer(modifier = Modifier.height(8.dp))
                        Text(report.aiSummary, style = MaterialTheme.typography.bodyMedium)
                    }
                }
            }
        }
        Spacer(modifier = Modifier.height(80.dp))
    }
}
